# Generated by Django 3.2.5 on 2021-07-19 23:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='demo', max_length=128)),
                ('create_datetime', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('create_author', models.CharField(default='demo', max_length=64)),
                ('update_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('update_author', models.CharField(default='demo', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='demo', max_length=128)),
                ('create_datetime', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('create_author', models.CharField(default='demo', max_length=64)),
                ('update_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('update_author', models.CharField(default='demo', max_length=64)),
                ('is_oncall', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oncall_department.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oncall_department.employee')),
            ],
            options={
                'db_table': 'employee_department_relationship',
                'unique_together': {('employee', 'department')},
            },
        ),
        migrations.AddField(
            model_name='department',
            name='employee',
            field=models.ManyToManyField(through='oncall_department.Employee_Department', to='oncall_department.Employee'),
        ),
    ]
